openapi: 3.0.3
info:
  title: DIP Sharing Board - OpenAPI 1.0
  description: |-
    This is a DIP sharing board Server based on the OpenAPI 1.0 specification.
    
    Some useful links:
    - [DIP Sharing Board github](https://github.com/DIP-Sharing-Board)
    - [DIP Sharing Board system design](https://github.com/DIP-Sharing-Board/system-design)
  contact:
    email: achikrab@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about DIP sharing board
  url: https://github.com/DIP-Sharing-Board
servers:
  - url: https://activity/api/v1
tags:
  - name: activity
    description: Operations about activity
    externalDocs:
      description: Find out more
      url: https://github.com/DIP-Sharing-Board
paths:
  /activities:
    get:
      tags:
        - activity
      summary: Get activities data
      description: Retrieve activities data by type and lastId.
      operationId: getActivities
      parameters:
        - name: type
          in: query
          description: Type of activity to get data for.
          required: true
          schema:
            type: string
            default: other
            enum:
              - camp
              - competition
              - other
        - name: lastId
          in: query
          description: ID of the last data provided before.
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidQueryResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseFailedResponse'

components:
  schemas:
    Activity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        link:
          type: string
          example: https://www.instagram.com/p/C6OWaPLvYcs/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==
        topic:
          type: string
          example: "WOW co-creation : “Design Thinking Being Innovator”"
        imageUrl:
          type: string
          example: https://instagram.fbkk5-6.fna.fbcdn.net/v/t51.29350-15/440664177_1081626339563006_6264858901487224383_n.jpg?stp=dst-jpg_e35&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDE4MDAuc2RyLmYyOTM1MCJ9&_nc_ht=instagram.fbkk5-6.fna.fbcdn.net&_nc_cat=102&_nc_ohc=XeqyL5x-u84Q7kNvgEoCMlc&edm=AFg4Q8wBAAAA&ccb=7-5&ig_cache_key=MzM1NDcxNzMyNjgwNzkzMjI5NQ%3D%3D.2-ccb7-5&oh=00_AYB0-zOt_K7dGiTY1FMWc4rxwBfdRwvLqO5xLNltBhF_4A&oe=668605EC&_nc_sid=0b30b7
        deadline:
          type: string
          example: "2024-05-04 16:30:00"
    ActivitiesResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                  $ref: '#/components/schemas/Activity'
      example:
        message: "success"
        code: 200
        data:
          - id: 10
            link: "https://www.instagram.com/p/C6OWaPLvYcs/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
            topic: "WOW co-creation : “Design Thinking Being Innovator”"
            imageUrl: "https://instagram.fbkk5-6.fna.fbcdn.net/v/t51.29350-15/440664177_1081626339563006_6264858901487224383_n.jpg?stp=dst-jpg_e35&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDE4MDAuc2RyLmYyOTM1MCJ9&_nc_ht=instagram.fbkk5-6.fna.fbcdn.net&_nc_cat=102&_nc_ohc=XeqyL5x-u84Q7kNvgEoCMlc&edm=AFg4Q8wBAAAA&ccb=7-5&ig_cache_key=MzM1NDcxNzMyNjgwNzkzMjI5NQ%3D%3D.2-ccb7-5&oh=00_AYB0-zOt_K7dGiTY1FMWc4rxwBfdRwvLqO5xLNltBhF_4A&oe=668605EC&_nc_sid=0b30b7"
            deadline: "2024-05-04 16:30:00"
          - id: 11
            link: "https://www.instagram.com/p/C6OWaPLvYcs/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA=="
            topic: "WOW co-creation : “Design Thinking Being Innovator”"
            imageUrl: "https://instagram.fbkk5-6.fna.fbcdn.net/v/t51.29350-15/440664177_1081626339563006_6264858901487224383_n.jpg?stp=dst-jpg_e35&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDE4MDAuc2RyLmYyOTM1MCJ9&_nc_ht=instagram.fbkk5-6.fna.fbcdn.net&_nc_cat=102&_nc_ohc=XeqyL5x-u84Q7kNvgEoCMlc&edm=AFg4Q8wBAAAA&ccb=7-5&ig_cache_key=MzM1NDcxNzMyNjgwNzkzMjI5NQ%3D%3D.2-ccb7-5&oh=00_AYB0-zOt_K7dGiTY1FMWc4rxwBfdRwvLqO5xLNltBhF_4A&oe=668605EC&_nc_sid=0b30b7"
            deadline: "2024-05-04 16:30:00"
    SuccessResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: "success"
      xml:
        name: '##default'
    InvalidQueryResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 400
        message:
          type: string
          example: '"Invalid type {query value}" or "Invalid format lastId"'
      xml:
        name: '##default'
    DatabaseFailedResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 500
        message:
          type: string
          example: "Database Failed"
      xml:
        name: '##default'